// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.frc2881.commands.scoring.HP;

import edu.wpi.first.wpilibj.command.Command;

import org.frc2881.Robot;

import edu.wpi.first.wpilibj.GenericHID;


/**
 * @param <AmpMonitor>
 *
 */
public class HPControlRollers<AmpMonitor> extends Command {

   // private AmpMonitor ampMonitor = new AmpMonitor(10.0, () -> Robot.intakeSubsystem.getHighestRollerCurrent());
    private boolean monitoringAmps;
    private double speedCap;
    private double joystickValue;
    private double programTime;
    private boolean joystickLeft;
    private boolean joystickRight;

    public HPControlRollers() {
        requires(Robot.intakeSubsystem);
}


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES


    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.log("Control Rollers has started");
        monitoringAmps = false;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if (!ampMonitor.isTriggered() && (programTime == 0 || timeSinceInitialized() > 500 ||
                joystickValue - Robot.oi.manipulator.getY(GenericHID.Hand.kLeft) >= 0.25)) {

            joystickLeft = Math.abs(Robot.oi.manipulator.getY(GenericHID.Hand.kLeft)) <= 0.15 &&
                    Robot.oi.manipulator.getX(GenericHID.Hand.kLeft) <= -0.15;
            joystickRight = Math.abs(Robot.oi.manipulator.getY(GenericHID.Hand.kLeft)) <= 0.15 &&
                    Robot.oi.manipulator.getX(GenericHID.Hand.kLeft) >= 0.15;

            if (joystickLeft || joystickRight) {
                System.out.println("turning");
                double turnSpeed = -Robot.oi.manipulator.getX(GenericHID.Hand.kLeft);
                Robot.intakeSubsystem.turnHPIntakeMotor(turnSpeed * .5);
            }

            else {
                double straightSpeed = -Robot.oi.manipulator.getY(GenericHID.Hand.kLeft);
                Robot.intakeSubsystem.hPIntakeMotor(straightSpeed);
                if (straightSpeed < -.35){
                    new SetClaw(LiftSubsystem.ClawState.OPEN).start();
                }
            }
        }

        else {
            Robot.intakeSubsystem.hPIntakeMotor(speedCap);
        }

        if (!monitoringAmps && timeSinceInitialized() > .2){
            ampMonitor.reset();
            monitoringAmps = true;
        }

        if (monitoringAmps && ampMonitor.isTriggered()) {
            Robot.log("HP Roller current limit exceeded");

            speedCap = 0.2;
            joystickValue = Robot.oi.manipulator.getY(GenericHID.Hand.kLeft);
            programTime = timeSinceInitialized();

            if (Math.abs(Robot.oi.manipulator.getX(GenericHID.Hand.kLeft)) <= 0.15 &&
                    Robot.oi.manipulator.getY(GenericHID.Hand.kLeft) > 0) {
                Robot.intakeSubsystem.hPIntakeMotor(-speedCap);
            }

            else if (Math.abs(Robot.oi.manipulator.getX(GenericHID.Hand.kLeft)) <= 0.15 &&
                    Robot.oi.manipulator.getY(GenericHID.Hand.kLeft) < 0 ){
                Robot.intakeSubsystem.hPIntakeMotor(speedCap);
            }

            else if (joystickLeft && Robot.oi.manipulator.getX(GenericHID.Hand.kLeft) < 0 ){
                Robot.intakeSubsystem.turnRollers(speedCap);
            }

            else if (joystickRight && Robot.oi.manipulator.getY(GenericHID.Hand.kLeft) > 0 ){
                Robot.intakeSubsystem.turnRollers(-speedCap);
            }

            new RumbleNo(Robot.oi.manipulator).start();
        }
}

  

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.log("HP Control Rollers has ended");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
