// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.subsystems;

import org.frc2881.commands.basic.drive.DriveWithJoysticks;

import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

/**
 *
 */
public class Drive extends Subsystem {

    public static final String IntakeLocation = null;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Spark leftFront;
    private Spark leftBack;
    private SpeedControllerGroup left;
    private Spark rightFront;
    private Spark rightBack;
    private SpeedControllerGroup right;
    private DifferentialDrive differentialDrive;
    

    public Drive() {
        leftFront = new Spark(8);
        addChild("Left Front",leftFront);
        leftFront.setInverted(false);
        
        leftBack = new Spark(9);
        addChild("Left Back",leftBack);
        leftBack.setInverted(false);
        
        left = new SpeedControllerGroup(leftFront, leftBack  );
        addChild("Left",left);
        
        
        rightFront = new Spark(6);
        addChild("Right Front",rightFront);
        rightFront.setInverted(false);
        
        rightBack = new Spark(7);
        addChild("Right Back",rightBack);
        rightBack.setInverted(false);
        
        right = new SpeedControllerGroup(rightFront, rightBack  );
        addChild("Right",right);
        
        
        differentialDrive = new DifferentialDrive(left, right);
        addChild("Differential Drive",differentialDrive);
        differentialDrive.setSafetyEnabled(true);
        differentialDrive.setExpiration(0.1);
        differentialDrive.setMaxOutput(1.0);

        

    }

    @Override
    public void initDefaultCommand() {

        setDefaultCommand(new DriveWithJoysticks());

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

	public double getLeftDistance() {
		return 0;
	}

	public double getRightDistance() {
		return 0;
	}

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

