// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.basic.rumble;

import edu.wpi.first.wpilibj.command.TimedCommand;

import org.frc2881.Robot;
import edu.wpi.first.wpilibj.GenericHID;

/**
 *
 */
public class RumbleJoysticks extends TimedCommand {
    public RumbleJoysticks() {
        super(.75);
    }

    @Override
    protected void initialize() {
        Robot.logInitialize(this);
        // Rumble things CODE
        Robot.oi.driver.setRumble(GenericHID.RumbleType.kRightRumble, .7);
        Robot.oi.driver.setRumble(GenericHID.RumbleType.kLeftRumble, .7);
    }
    
    @Override
    protected void end() {
        Robot.logEnd(this);
        Robot.oi.driver.setRumble(GenericHID.RumbleType.kRightRumble, 0);
        Robot.oi.driver.setRumble(GenericHID.RumbleType.kLeftRumble, 0);
    }
}
