// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.basic.rumble;

import org.frc2881.OI;
import org.frc2881.Robot;

import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.GenericHID.RumbleType;
import edu.wpi.first.wpilibj.command.Command;

/**o
 *
 */
public class RumbleDriver extends Command {
   // Called just before this Command runs the first time
   @Override
   protected void initialize() {
       Robot.log("RumbleDriver has started");
       Robot.oi.driver.setRumble(RumbleType.kRightRumble, .7);
   }

   // Called repeatedly when this Command is scheduled to run
   @Override
   protected void execute() {
   }

   // Make this return true when this Command no longer needs to run execute()
   @Override
   protected boolean isFinished() {
       double leftY = -Robot.oi.driver.getY(Hand.kLeft);
       double leftX = -Robot.oi.driver.getX(Hand.kLeft);
       double rightY = -Robot.oi.driver.getY(Hand.kRight);
       double rightX = -Robot.oi.driver.getX(Hand.kRight);

       return (Math.abs(rightX) > OI.DEADBAND) || (Math.abs(leftX) > OI.DEADBAND) ||
               (Math.abs(rightY) > OI.DEADBAND) || (Math.abs(leftY) > OI.DEADBAND);
   }

   // Called once after isFinished returns true
   @Override
   protected void end() {
       Robot.oi.driver.setRumble(RumbleType.kRightRumble, 0);
       Robot.log("RumbleDriver has finished");
   }
}
