// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.basic.rumble;

import org.frc2881.Robot;
import org.frc2881.subsystems.PrettyLights;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.command.TimedCommand;

/**
 *
 */
public class RumbleYes extends TimedCommand {

    private final XboxController controller;

    public RumbleYes(XboxController controller) {
        super(.6);
        requires(Robot.prettyLights);
        this.controller = controller;
    }

    @Override
    protected void initialize() {
        Robot.logInitialize(this);
        controller.setRumble(GenericHID.RumbleType.kRightRumble, 1);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        Robot.prettyLights.setColor(PrettyLights.green);

        double time = timeSinceInitialized();
        if (time <= 0.2) {
            controller.setRumble(GenericHID.RumbleType.kRightRumble, 1);
        } else {
            controller.setRumble(GenericHID.RumbleType.kRightRumble, 0);
        }
    }

    @Override

    protected void end() {
        controller.setRumble(GenericHID.RumbleType.kRightRumble, 0);
        Robot.logEnd(this);
    }
}
