// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.scoring.arm;

import org.frc2881.Robot;
import org.frc2881.subsystems.Arm.WristState;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class ArmWrist extends Command {

    private WristState state;

    public ArmWrist(WristState state) {
        requires(Robot.arm);
        this.state = state;
    }

    @Override
    protected void initialize() {
        Robot.logInitialize(this);
        Robot.arm.moveWrist(state);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return true;
    }

    @Override
    protected void end() {
        Robot.logEnd(this);
    }
}
