// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.scoring.cargo;

import edu.wpi.first.wpilibj.command.Command;

import org.frc2881.Robot;
import org.frc2881.commands.basic.rumble.RumbleNo;
import org.frc2881.controllers.PS4;
import org.frc2881.subsystems.Intake.RollerDirection;
import org.frc2881.utils.AmpMonitor;

/**
 *
 */
public class CargoIntake extends Command {

    private AmpMonitor ampMonitor = new AmpMonitor(10, () -> Robot.intake.getCargoRollerCurrent());
    private boolean monitoringAmps;
    private double programTime;
    private double triggerValue;
    private static final double speedCap = 0;


    public CargoIntake() {
        requires (Robot.intake);

    }

    @Override
    protected void initialize() {
        Robot.logInitialize(this);
        monitoringAmps = false;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {

        //Robot.intake.cargoRollers(Robot.oi.manipulator.getRawAxis(PS4.LEFT_TRIGGER), RollerDirection.INTAKE);

        if (!ampMonitor.isTriggered() && (programTime == 0 || timeSinceInitialized() > 500 ||
                triggerValue - Robot.oi.manipulator.getRawAxis(PS4.LEFT_TRIGGER) >= 0.25)) {
            Robot.intake.cargoRollers(Robot.oi.manipulator.getRawAxis(PS4.LEFT_TRIGGER), RollerDirection.INTAKE);
        }

        else {
            Robot.intake.cargoRollers(speedCap, RollerDirection.INTAKE);
        }

        if (!monitoringAmps && timeSinceInitialized() > .2){
            ampMonitor.reset();
            monitoringAmps = true;
        }

        if (monitoringAmps && ampMonitor.isTriggered()) {
            Robot.log("Cargo Roller current limit exceeded");

            triggerValue = Robot.oi.manipulator.getRawAxis(PS4.LEFT_TRIGGER);
            programTime = timeSinceInitialized();
            Robot.intake.cargoRollers(speedCap, RollerDirection.INTAKE);

            new RumbleNo(Robot.oi.manipulator).start();
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    @Override
    protected void end() {
        Robot.intake.cargoRollers(0, RollerDirection.BUTTON);
        Robot.logEnd(this);
    }
} 