// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.scoring.cargo;

import org.frc2881.Robot;
//import org.frc2881.commands.scoring.arm.ArmWrist;
//import org.frc2881.subsystems.Arm.WristState;
//import edu.wpi.first.wpilibj.command.WaitCommand;
import org.frc2881.subsystems.Intake.RollerDirection;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class CargoPlace extends CommandGroup {

    public CargoPlace() {
        //addSequential(new ArmWrist(WristState.DOWN));
        //addSequential(new WaitCommand("Cargo Wait", 1));
        addSequential(new CargoSetRollers(1.0, RollerDirection.EJECT));

    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    @Override
    protected void end() {
        Robot.logEnd(this);
        Robot.intake.cargoRollers(0, RollerDirection.EJECT);
        //Robot.arm.moveWrist(WristState.UP);
    }

    @Override
    protected void interrupted() {
        end();
    }
}
