// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.scoring;

import org.frc2881.Robot;
import org.frc2881.commands.basic.drive.DriveForward;
import org.frc2881.commands.scoring.arm.ArmToHeight;
import org.frc2881.commands.scoring.hp.HPGrabber;
import org.frc2881.commands.scoring.hp.HPTongue;
import org.frc2881.subsystems.Arm.ArmValue;
import org.frc2881.subsystems.Intake.GrabberState;
import org.frc2881.subsystems.Intake.TongueState;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class HabEscape extends CommandGroup {

    public HabEscape() {
        Robot.logInitialize(this);
        addSequential(new HPTongue(TongueState.OUT));
        addSequential(new HPGrabber(GrabberState.GRAB));
        addSequential(new ArmToHeight(ArmValue.VALUE, 5, false));
        addSequential(new DriveForward(0.65));
    }
}
