// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.basic.drive;

import org.frc2881.Robot;
import org.frc2881.commands.basic.rumble.RumbleYes;
import org.frc2881.utils.NTValue;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 
 */
public class AutonomousRocketAlignment extends CommandGroup {
    public AutonomousRocketAlignment() {
        Robot.logInitialize(this);
        if (NTValue.distanceToMove() < 3) {
            addSequential(new SidewaysSequence(NTValue.distanceToMove()), 1);
        }
        
        addSequential(new RumbleYes(Robot.oi.manipulator));
    }
}
