// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.basic.drive;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SendableBuilder;

import org.frc2881.Robot;

/**
 *
 */
public class DriveForward extends Command {
    private double speedSole = 0.58;
    private double distance;

    public DriveForward(double distance) {
        // TODO: implement this
        this.distance = distance;
        requires(Robot.drive);
        this.distance = distance;
    }

    private static double computeTimeout(double distance) {
        //Give the robot 1 second to get started then assume it travels at 3 ft/second (in practice it's faster)
        return 1.0 + (Math.abs(distance) / 3.0);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        
            return true;
    }

    @Override
    protected void end() {
        Robot.logEnd(this);
        Robot.drive.tankDrive(0, 0, 0);
        
    }
}