// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.frc2881.commands.basic.drive;

import org.frc2881.Robot;
import org.frc2881.subsystems.Drive;

import edu.wpi.first.wpilibj.command.InstantCommand;

/**
 *
 */
public class IntakeSetAsBack extends InstantCommand {

    @Override
    protected void initialize() {
        Robot.logInitialize(this);
        Robot.drive.setIntakeLocation(Drive.IntakeLocation.BACK);
        //Prints in the driver station
        Robot.log("Intake has been set to BACK.");
        Robot.log("Meaning the BACK of the robot is now the FRONT");
    }
}
